version: '3.8'

services:
  # productsapi:
  #   image: products-api
  #   container_name: products-api
  #   ports:
  #     - "3000:443"
  #   restart: always 

  # products-next:
  #   image: products-nextjs
  #   container_name: products-frontend
  #   ports:
  #     - "4000:4000"
  #   restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=40c79244-e384-40e5-a317-19742c22b332
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
