name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: murilothebr
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_TOKEN}}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ubuntu
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Build and push container 1
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ProductApi/ProductApi/Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/products-api:latest

    - name: Build and push container 2
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/products-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Copy docker-compose.yml to server
      run: scp docker-compose.yml ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:~/docker-compose.yml

    - name: SSH and run docker-compose up
      run: ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} 'cd ~/ && docker-compose up -d'
